image: golang:1.19-alpine

default:
  tags:
    - linux-local

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: go test -v

build:
  stage: build
  script:
    - mkdir -p bin
    - go build -o bin ./
  artifacts:
    paths:
      - bin

deploy-to-s3:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  script:
    - aws --version